name = "v50"
compatibility_date = "2026-05-18"
pages_build_output_dir = "public"

[ai]
binding = "AI"
remote = true

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "401f3985b7fb47358297af1d698594be"
preview_id = "ad0f66c30024488b84e52bd4d1e51f61"
